### ISSUE TITLE
Push files to subfolder of root path?

### ISSUE THREAD

**Issue by quinn-p-mchugh** [afazio1/obsidian-markdown-blogger#2]
Hi there,

Didn't realize how much I need a tool like this until now. Very handy! Thank you for your efforts.

It seems like files can only be pushed to one path at the moment. Are there plans to support pushing files to a subfolder of the root path?

**Comment by afazio1** [comment]
Hi, I'm glad you're finding the plugin useful!

I was thinking of adding a way for a user to type a path in the push and pull commands. Something like:
**Push: ** `Desktop/code-projects/blog`

This would allow you to push to multiple paths quickly. 

My plugin still has to be approved by Obsidian, so I'm waiting to release new features. I'll mark this as a feature request.
Thanks for the feedback!

**Comment by quinn-p-mchugh** [comment]
Sounds great!

FYI: I came across [Obsidian GitHub Publisher](https://github.com/ObsidianPublisher/obsidian-github-publisher) a little while back. Might yield some ideas/insights on where to take this plugin.

**Comment by pedenys** [comment]
Hello @quinn-p-mchugh thank you for your work. I was looking for a plug-in like this to handle manual updates to my blog. I’ve added locally the ability to copy/paste/pull parent file folders on your plugin. I would gladly submit a PR once it’s stable if you can have a look at it or update the feature if you want, let me know.
