### ISSUE TITLE
Support for GitHub Pages

### ISSUE THREAD

**Issue by Malix-Off** [afazio1/obsidian-markdown-blogger#3]
Hello!
Does this support GitHub Pages?
If not, would it be possible to implement its support?
Thanks!

**Comment by afazio1** [comment]
Hi, thanks for the question!

Markdown Blogger does not make any assumptions about the tech you are using to build / deploy your site. It is simply meant to quickly transfer markdown files between Obsidian and a local project folder. 

If you are looking to set up your GitHub pages repo to render markdown, here is a resource I found: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll

I hope this helps!
